docs: add `astro` example
unocss/unocss pull request #1423
Opened 2022-08-16 04:05 UTC by Dunqing

close: #1402

Just insert the following code into the *.astro page or layout component.

```html
<script>import 'uno.css'</script>.
```

### Note: 

The imported 'uno.css' must be included on all pages or layouts that use `unocss`, otherwise it will not take effect.

I'm not sure if this is the best solution, but it should be the simplest one that requires no changes at this time.

2022-08-21 14:23 UTC, antfu requested changes

2022-08-21 14:23 UTC, antfu commented on examples/astro/src/components/Card.astro
> +	}
Could we remove all these inline styles to use UnoCSS exclusively?

2022-08-21 14:23 UTC, antfu commented on examples/astro/README.md
> +# Welcome to [Astro](https://astro.build)
We might remove the default readme, but instead, explain about how to integrate UnoCSS intro Astro and with the caveats you mentioned.

2022-08-21 14:23 UTC, antfu commented on examples/astro/tsconfig.json
> +    // Astro will directly run your TypeScript code, no transpilation needed.
We could remove these comments

2022-08-22 09:28 UTC, antfu commented
Thanks for the initiative. I have extended this PR to also introduce a new Astro integration so the requirement of importing `uno.css` is no longer a case.

2022-08-22 09:29 UTC, antfu approved these changes

2022-08-22 09:35 UTC, merged

2022-08-22 11:05 UTC, Dunqing commented
> Thanks for the initiative. I have extended this PR to also introduce a new Astro integration so the requirement of importing `uno.css` is no longer a case.

Thank you, this is the better solution!

2022-11-07 10:04 UTC, aspiiire commented
With the integration it doesn't build for me, it gives:
```
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks
This is likely an internal bug of unocss vite plugin
```
If I remove it from the integration and import unocss/vite on astro.config.mjs under vite.plugins and add import 'uno.css' everything works fine why?