chore: upgrade vite version
unocss/unocss pull request #1490
Opened 2022-08-29 07:34 UTC by sudongyuer

#1489

2022-08-29 07:57 UTC, antfu requested changes

2022-08-29 07:57 UTC, antfu commented on pnpm-lock.yaml
> -lockfileVersion: 5.4
Please enable corepack

2022-08-29 08:48 UTC, sudongyuer commented on pnpm-lock.yaml
> -lockfileVersion: 5.4
Do i solve it tony ?

2022-08-29 09:13 UTC, antfu approved these changes

2022-08-31 16:35 UTC, antfu commented
The test is failing. I guess the override is still needed to make sure a single version of Vite installed.

2022-09-01 02:44 UTC, sudongyuer commented
> 

#1505

2022-09-01 02:44 UTC, closed without merging