fix(preset-mini): handle value is 0
unocss/unocss pull request #2153
Opened 2023-02-05 13:32 UTC by zyyv

close #2152

2023-02-05 18:29 UTC, sibbng requested changes

2023-02-05 18:29 UTC, sibbng commented on packages/preset-mini/src/_theme/misc.ts
> +  none: '0',
```suggestion
  none: '0s',
```

0 is not a valid duration
![image](https://user-images.githubusercontent.com/19991745/216837434-332b43f9-5e7d-4a35-933b-8a8ba8c7de2a.png)

2023-02-06 00:12 UTC, chu121su12 approved these changes

2023-02-06 07:48 UTC, Hongbusi approved these changes

2023-02-06 08:13 UTC, merged