feat(vscode): remove unocss.root and use auto-detection
unocss/unocss pull request #3069
Opened 2023-09-03 15:05 UTC by Simon-He95

With the popularity of monorepo, more and more libraries may use this mode, but it is very troublesome to configure `settings.json` additionally. I hope to automate changes more intelligently based on the `unocss.config` of my current project.

2023-09-20 04:16 UTC, antfu requested changes

2023-09-20 04:16 UTC, antfu commented on packages/vscode/src/index.ts
> +    const target = await findUp(['package.json'], { cwd: url })
Maybe we should search for the uno.config directly instead.

2023-09-20 04:16 UTC, antfu commented on packages/vscode/src/index.ts
> +    const cwd = target.slice(0, -13)
Not in favor of this magic number, can we use `basename`?

2023-09-20 04:16 UTC, antfu commented on packages/vscode/src/index.ts
> +  const cacheMap = new Set()
We should also cache for file resolution, so we don't need to run `findUp` every time user navigate to the file.

2023-09-20 04:16 UTC, antfu commented on packages/vscode/src/index.ts
> +  const cacheMap = new Set()
In addition, we could also listen to the fs on adding/removing the config file and purge the cache.

2023-09-20 04:16 UTC, antfu commented on packages/vscode/src/index.ts
> +    if (/node_modules/.test(url))
I think this might be better to be configurable, as an `exclude` option maybe.

2023-09-20 04:18 UTC, antfu commented
Also I don't think we should completely remove the `unocss.root` support, we could have this as a smart default when root is not specified, but keep the original behaviour without breaking change.

2023-09-20 07:36 UTC, Simon-He95 commented
> Also I don't think we should completely remove the `unocss.root` support, we could have this as a smart default when root is not specified, but keep the original behaviour without breaking change.

Thank you for your review, I made some adjustments, please help to check it out

2023-09-20 11:48 UTC, antfu requested changes

2023-09-20 11:48 UTC, antfu commented on test/assets/variant-group.vue
> +const _c = a - (b - a - b)
Please revert this

2023-09-20 11:48 UTC, antfu commented on packages/vscode/package.json
> +  "name": "unocss",
This should only be changed in dev, should not be committed

2023-09-20 11:48 UTC, antfu commented on packages/vscode/src/index.ts
> +import { watch } from 'fs'
Better use `createFileSystemWatcher` https://code.visualstudio.com/api/references/vscode-api#workspace

2023-09-20 11:48 UTC, antfu commented on packages/vscode/src/index.ts
> +  const include = config.get<string | string[]>('include')
We need to add these two configs in package.json

2023-09-20 13:59 UTC, Simon-He95 commented on packages/vscode/src/index.ts
> +import { watch } from 'fs'
Learned

2023-09-20 14:25 UTC, Simon-He95 commented
Do you think it is necessary for us to monitor the file name changes or new creations of uno.config?

2023-09-26 06:46 UTC, antfu approved these changes

2023-09-26 06:57 UTC, antfu commented
Nice work! Thanks

2023-09-26 07:00 UTC, merged