feat: add `appearance-auto` utility
unocss/unocss pull request #3470
Opened 2023-12-28 17:09 UTC by navorite

this adds `appearance-auto` to be compatible with TailwindCSS v3.4.0

2023-12-29 08:34 UTC, zyyv requested changes

2023-12-29 08:34 UTC, zyyv commented on packages/preset-mini/src/_rules/behaviors.ts
> +  [/^appearance-(none|auto)$/, ([, m]) => ({ '-webkit-appearance': m, 'appearance': m }), { autocomplete: 'appearance-(none|auto)' }],
Please rewrite it as a static rule. Uno handle the static rules faster than dynamic rules.

2023-12-29 10:02 UTC, zyyv approved these changes

2024-01-01 04:20 UTC, antfu approved these changes

2024-01-01 04:25 UTC, merged